#!/usr/bin/env node
/**
 * Put cc-agent on a schedule (4.4.1).
 *
 *   "Must read session logs on a schedule, with no action from Josh."
 *
 * The agent itself was built, calibrated and documented — and nothing ran it. The runbook asked Josh
 * to create a Task Scheduler entry by hand, which is the class of instruction that never gets
 * carried out, and the input silently produced nothing while looking finished. Zero Claude Code
 * candidates ever arrived.
 *
 * "With no action from Josh" cannot mean zero action ever: the logs are on his machine and nothing
 * in Supabase can reach them. It means no action per RUN. So the honest reading is one setup command
 * and then never again, which is what this is.
 *
 *   node cc-agent/install.mjs              # set it up, ask for anything missing
 *   node cc-agent/install.mjs --status     # is it scheduled, and when did it last run
 *   node cc-agent/install.mjs --uninstall  # remove the schedule; the agent stays
 *
 * Windows uses schtasks, macOS launchd, Linux a systemd user timer. Credentials go in a file beside
 * the agent rather than into the task definition: `schtasks /query` prints arguments in full, and a
 * service-role key does not belong in something that prints.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import readline from "node:readline/promises";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const AGENT = path.join(HERE, "index.mjs");
const ENV_FILE = path.join(HERE, ".env");
const TASK_NAME = "ThoughtPilotClaudeCode";
const RUN_AT = "09:15"; // after the working day starts, before the queue tick matters

const arg = process.argv[2] ?? "";

/* ── Credentials ──────────────────────────────────────────────────────────── */

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) return {};
  const out = {};
  for (const line of fs.readFileSync(ENV_FILE, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

async function ensureCredentials() {
  const existing = { ...readEnvFile(), ...process.env };
  const needed = ["CONTENT_SYSTEM_URL", "CONTENT_SYSTEM_KEY"];
  const missing = needed.filter((k) => !existing[k]);
  if (missing.length === 0) return existing;

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answers = {};
  console.log("\nTwo values are needed. Both are in your Supabase project settings.\n");
  for (const key of missing) {
    const hint = key === "CONTENT_SYSTEM_URL"
      ? "  e.g. https://abcdefgh.supabase.co/functions/v1"
      : "  the service_role key (Project Settings → API)";
    console.log(hint);
    answers[key] = (await rl.question(`${key}: `)).trim();
    console.log();
  }
  rl.close();

  const merged = { ...readEnvFile(), ...answers };
  fs.writeFileSync(
    ENV_FILE,
    "# cc-agent credentials. Not in version control — see .gitignore.\n" +
      Object.entries(merged).map(([k, v]) => `${k}=${v}`).join("\n") + "\n",
    { mode: 0o600 },
  );
  console.log(`Saved to ${ENV_FILE} (readable only by you).\n`);
  return { ...existing, ...answers };
}

/* ── Schedulers ───────────────────────────────────────────────────────────── */

/**
 * A shim, because none of the three schedulers can source an env file.
 *
 * It also means the credentials never appear in a task definition, a plist, or the output of
 * `schtasks /query` — which prints arguments in full to anyone who asks.
 */
function writeRunner() {
  const runner = path.join(HERE, "run-scheduled.mjs");
  fs.writeFileSync(
    runner,
    `#!/usr/bin/env node
// Generated by install.mjs. Loads .env, then runs the agent. Safe to delete and regenerate.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const envFile = path.join(here, ".env");
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, "utf8").split("\\n")) {
    const m = line.match(/^\\s*([A-Z_]+)\\s*=\\s*(.*)\\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}
await import(path.join(here, "index.mjs"));
`,
    { mode: 0o700 },
  );
  return runner;
}

function installWindows(runner) {
  execFileSync("schtasks", [
    "/Create", "/F",
    "/SC", "DAILY",
    "/ST", RUN_AT,
    "/TN", TASK_NAME,
    "/TR", `"${process.execPath}" "${runner}"`,
  ], { stdio: "inherit" });
  return `Windows Task Scheduler — "${TASK_NAME}", daily at ${RUN_AT}`;
}

function installMac(runner) {
  const label = "com.thoughtpilot.cc-agent";
  const plistPath = path.join(os.homedir(), "Library", "LaunchAgents", `${label}.plist`);
  const [hour, minute] = RUN_AT.split(":").map(Number);

  fs.mkdirSync(path.dirname(plistPath), { recursive: true });
  fs.writeFileSync(
    plistPath,
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array><string>${process.execPath}</string><string>${runner}</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>${hour}</integer><key>Minute</key><integer>${minute}</integer></dict>
  <key>StandardErrorPath</key><string>${path.join(HERE, "cc-agent.log")}</string>
  <key>StandardOutPath</key><string>${path.join(HERE, "cc-agent.log")}</string>
</dict></plist>
`,
  );
  try { execFileSync("launchctl", ["unload", plistPath], { stdio: "ignore" }); } catch { /* first run */ }
  execFileSync("launchctl", ["load", plistPath], { stdio: "inherit" });
  return `launchd — ${label}, daily at ${RUN_AT}`;
}

function installLinux(runner) {
  const dir = path.join(os.homedir(), ".config", "systemd", "user");
  fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(path.join(dir, "cc-agent.service"),
    `[Unit]\nDescription=Thought Pilot — read Claude Code sessions (4.4)\n\n` +
    `[Service]\nType=oneshot\nExecStart=${process.execPath} ${runner}\n`);
  fs.writeFileSync(path.join(dir, "cc-agent.timer"),
    `[Unit]\nDescription=Daily Claude Code session read\n\n` +
    `[Timer]\nOnCalendar=*-*-* ${RUN_AT}:00\nPersistent=true\n\n` +
    `[Install]\nWantedBy=timers.target\n`);

  execFileSync("systemctl", ["--user", "daemon-reload"], { stdio: "inherit" });
  execFileSync("systemctl", ["--user", "enable", "--now", "cc-agent.timer"], { stdio: "inherit" });
  return `systemd user timer — cc-agent.timer, daily at ${RUN_AT}`;
}

function uninstall() {
  try {
    if (process.platform === "win32") {
      execFileSync("schtasks", ["/Delete", "/F", "/TN", TASK_NAME], { stdio: "inherit" });
    } else if (process.platform === "darwin") {
      const p = path.join(os.homedir(), "Library", "LaunchAgents", "com.thoughtpilot.cc-agent.plist");
      execFileSync("launchctl", ["unload", p], { stdio: "ignore" });
      fs.rmSync(p, { force: true });
    } else {
      execFileSync("systemctl", ["--user", "disable", "--now", "cc-agent.timer"], { stdio: "inherit" });
    }
    console.log("Schedule removed. The agent itself is untouched, and so is anything it has sent.");
  } catch (err) {
    console.error(`Could not remove it: ${err.message}`);
    process.exit(1);
  }
}

function status() {
  try {
    if (process.platform === "win32") {
      execFileSync("schtasks", ["/Query", "/TN", TASK_NAME, "/V", "/FO", "LIST"], { stdio: "inherit" });
    } else if (process.platform === "darwin") {
      execFileSync("launchctl", ["list", "com.thoughtpilot.cc-agent"], { stdio: "inherit" });
    } else {
      execFileSync("systemctl", ["--user", "status", "cc-agent.timer"], { stdio: "inherit" });
    }
  } catch {
    console.log("Not scheduled. Run `node cc-agent/install.mjs` to set it up.");
  }
}

/* ── Main ─────────────────────────────────────────────────────────────────── */

if (arg === "--uninstall") { uninstall(); process.exit(0); }
if (arg === "--status") { status(); process.exit(0); }

console.log("cc-agent — scheduling the Claude Code reader (4.4.1)\n");

const env = await ensureCredentials();
const runner = writeRunner();

let where;
try {
  where = process.platform === "win32"
    ? installWindows(runner)
    : process.platform === "darwin"
    ? installMac(runner)
    : installLinux(runner);
} catch (err) {
  console.error(`\nCould not create the schedule: ${err.message}`);
  console.error("Run this from a normal terminal (not an editor's console) and try again.");
  process.exit(1);
}

console.log(`\nScheduled: ${where}\n`);

// Prove the wiring rather than declaring it. A dry run reads the real corpus and sends nothing, so
// a wrong URL or key shows up now instead of silently producing nothing for a fortnight.
console.log("Checking it actually works — reading your sessions, sending nothing:\n");
try {
  execFileSync(process.execPath, [AGENT, "--dry-run"], {
    stdio: "inherit",
    env: { ...process.env, ...env },
  });
} catch {
  console.error("\nThe dry run failed. The schedule is in place, but fix the above before trusting it.");
  process.exit(1);
}

console.log(
  `\nDone. It runs daily at ${RUN_AT}.\n\n` +
    `Before trusting the threshold, run:  node eval/calibrate-cc.mjs\n` +
    `4.4.3 is explicit that ten candidates a day is worse than none — the default bar was set\n` +
    `against a corpus that is not yours.\n\n` +
    `  --status     is it scheduled, when did it last run\n` +
    `  --uninstall  stop it\n`,
);
