#!/usr/bin/env node
/**
 * Put cc-agent on a schedule (4.4.1).
 *
 *   "Must read session logs on a schedule, with no action from Josh."
 *
 * The agent itself was built, calibrated and documented — and nothing ran it. The runbook asked Josh
 * to create a Task Scheduler entry by hand, which is the class of instruction that never gets
 * carried out, and the input silently produced nothing while looking finished. Zero Claude Code
 * candidates ever arrived.
 *
 * "With no action from Josh" cannot mean zero action ever: the logs are on his machine and nothing
 * in Supabase can reach them. It means no action per RUN. So the honest reading is one setup command
 * and then never again, which is what this is.
 *
 *   node cc-agent/install.mjs              # set it up, ask for anything missing
 *   node cc-agent/install.mjs --status     # is it scheduled, and when did it last run
 *   node cc-agent/install.mjs --uninstall  # remove the schedule; the agent stays
 *
 * Windows uses schtasks, macOS launchd, Linux a systemd user timer. Credentials go in a file beside
 * the agent rather than into the task definition: `schtasks /query` prints arguments in full, and a
 * service-role key does not belong in something that prints.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import readline from "node:readline/promises";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { findSessions } from "./index.mjs";
import { blank, c, done, failed, hint, no, ok, step, title, warn } from "./ui.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const AGENT = path.join(HERE, "index.mjs");
const ENV_FILE = path.join(HERE, ".env");
const TASK_NAME = "ThoughtPilotClaudeCode";
const RUN_AT = "09:15"; // after the working day starts, before the queue tick matters

const arg = process.argv[2] ?? "";

/* ── Credentials ──────────────────────────────────────────────────────────── */

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) return {};
  const out = {};
  for (const line of fs.readFileSync(ENV_FILE, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

async function ensureCredentials() {
  const existing = { ...readEnvFile(), ...process.env };
  const needed = ["CONTENT_SYSTEM_URL", "CONTENT_SYSTEM_KEY"];
  const missing = needed.filter((k) => !existing[k]);
  if (missing.length === 0) return existing;

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answers = {};
  console.log("\nTwo values are needed. Both are in your Supabase project settings.\n");
  for (const key of missing) {
    const hint = key === "CONTENT_SYSTEM_URL"
      ? "  e.g. https://abcdefgh.supabase.co/functions/v1"
      : "  the service_role key (Project Settings → API)";
    console.log(hint);
    answers[key] = (await rl.question(`${key}: `)).trim();
    console.log();
  }
  rl.close();

  const merged = { ...readEnvFile(), ...answers };
  fs.writeFileSync(
    ENV_FILE,
    "# cc-agent credentials. Not in version control — see .gitignore.\n" +
      Object.entries(merged).map(([k, v]) => `${k}=${v}`).join("\n") + "\n",
    { mode: 0o600 },
  );
  console.log(`Saved to ${ENV_FILE} (readable only by you).\n`);
  return { ...existing, ...answers };
}

/* ── Schedulers ───────────────────────────────────────────────────────────── */

/**
 * A shim, because none of the three schedulers can source an env file.
 *
 * It also means the credentials never appear in a task definition, a plist, or the output of
 * `schtasks /query` — which prints arguments in full to anyone who asks.
 */
function writeRunner() {
  const runner = path.join(HERE, "run-scheduled.mjs");
  fs.writeFileSync(
    runner,
    `#!/usr/bin/env node
// Generated by install.mjs. Loads .env, then runs the agent. Safe to delete and regenerate.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const envFile = path.join(here, ".env");
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, "utf8").split("\\n")) {
    const m = line.match(/^\\s*([A-Z_]+)\\s*=\\s*(.*)\\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}
await import(path.join(here, "index.mjs"));
`,
    { mode: 0o700 },
  );
  return runner;
}

function installWindows(runner) {
  execFileSync("schtasks", [
    "/Create", "/F",
    "/SC", "DAILY",
    "/ST", RUN_AT,
    "/TN", TASK_NAME,
    "/TR", `"${process.execPath}" "${runner}"`,
  ], { stdio: "inherit" });
  return `Windows Task Scheduler — "${TASK_NAME}", daily at ${RUN_AT}`;
}

function installMac(runner) {
  const label = "com.thoughtpilot.cc-agent";
  const plistPath = path.join(os.homedir(), "Library", "LaunchAgents", `${label}.plist`);
  const [hour, minute] = RUN_AT.split(":").map(Number);

  fs.mkdirSync(path.dirname(plistPath), { recursive: true });
  fs.writeFileSync(
    plistPath,
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array><string>${process.execPath}</string><string>${runner}</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>${hour}</integer><key>Minute</key><integer>${minute}</integer></dict>
  <key>StandardErrorPath</key><string>${path.join(HERE, "cc-agent.log")}</string>
  <key>StandardOutPath</key><string>${path.join(HERE, "cc-agent.log")}</string>
</dict></plist>
`,
  );
  try { execFileSync("launchctl", ["unload", plistPath], { stdio: "ignore" }); } catch { /* first run */ }
  execFileSync("launchctl", ["load", plistPath], { stdio: "inherit" });
  return `launchd — ${label}, daily at ${RUN_AT}`;
}

function installLinux(runner) {
  const dir = path.join(os.homedir(), ".config", "systemd", "user");
  fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(path.join(dir, "cc-agent.service"),
    `[Unit]\nDescription=Thought Pilot — read Claude Code sessions (4.4)\n\n` +
    `[Service]\nType=oneshot\nExecStart=${process.execPath} ${runner}\n`);
  fs.writeFileSync(path.join(dir, "cc-agent.timer"),
    `[Unit]\nDescription=Daily Claude Code session read\n\n` +
    `[Timer]\nOnCalendar=*-*-* ${RUN_AT}:00\nPersistent=true\n\n` +
    `[Install]\nWantedBy=timers.target\n`);

  execFileSync("systemctl", ["--user", "daemon-reload"], { stdio: "inherit" });
  execFileSync("systemctl", ["--user", "enable", "--now", "cc-agent.timer"], { stdio: "inherit" });
  return `systemd user timer — cc-agent.timer, daily at ${RUN_AT}`;
}

function uninstall() {
  try {
    if (process.platform === "win32") {
      execFileSync("schtasks", ["/Delete", "/F", "/TN", TASK_NAME], { stdio: "inherit" });
    } else if (process.platform === "darwin") {
      const p = path.join(os.homedir(), "Library", "LaunchAgents", "com.thoughtpilot.cc-agent.plist");
      execFileSync("launchctl", ["unload", p], { stdio: "ignore" });
      fs.rmSync(p, { force: true });
    } else {
      execFileSync("systemctl", ["--user", "disable", "--now", "cc-agent.timer"], { stdio: "inherit" });
    }
    console.log("Schedule removed. The agent itself is untouched, and so is anything it has sent.");
  } catch (err) {
    console.error(`Could not remove it: ${err.message}`);
    process.exit(1);
  }
}

function status() {
  try {
    if (process.platform === "win32") {
      execFileSync("schtasks", ["/Query", "/TN", TASK_NAME, "/V", "/FO", "LIST"], { stdio: "inherit" });
    } else if (process.platform === "darwin") {
      execFileSync("launchctl", ["list", "com.thoughtpilot.cc-agent"], { stdio: "inherit" });
    } else {
      execFileSync("systemctl", ["--user", "status", "cc-agent.timer"], { stdio: "inherit" });
    }
  } catch {
    console.log("Not scheduled. Run `node cc-agent/install.mjs` to set it up.");
  }
}

/* ── Doctor ───────────────────────────────────────────────────────────────── */

/**
 * Every reason this can fail to work, checked in the order it would fail.
 *
 * The failure this exists to prevent is the one that already happened once: the agent was built,
 * calibrated and documented, nothing ran it, and the input produced nothing for weeks while looking
 * finished. A silent input is indistinguishable from a quiet week — 4.4.2 says a week that produces
 * nothing is a PASS — so the only way to tell them apart is to check the plumbing directly.
 *
 * Returns true when everything is in place, so setup can use the same checks rather than repeating
 * them differently.
 */
async function doctor({ quiet = false } = {}) {
  const say = { ok: quiet ? () => {} : ok, no, warn, hint };
  let healthy = true;

  // 1. Node. The agent uses top-level await and native fetch.
  const major = Number(process.versions.node.split(".")[0]);
  if (major >= 18) say.ok(`Node ${process.versions.node}`);
  else {
    healthy = false;
    no(`Node ${process.versions.node}`);
    hint("The agent needs Node 18 or newer for fetch and top-level await.");
  }

  // 2. The agent itself.
  if (fs.existsSync(AGENT)) say.ok("Agent present", path.basename(AGENT));
  else {
    healthy = false;
    no("Agent missing");
    hint(`Expected it at ${AGENT}`);
  }

  // 3. Something to read. Zero sessions is not a failure — it is a machine that has not been used
  //    for this work yet — but it is worth saying out loud rather than discovering in a fortnight.
  const logDir = path.join(os.homedir(), ".claude", "projects");
  if (!fs.existsSync(logDir)) {
    warn("No Claude Code logs on this machine");
    hint(`Looked in ${logDir}
` +
      "Nothing to read yet. Install it on the machine where the real work happens.");
  } else {
    const sessions = findSessions(logDir);
    if (sessions.length === 0) {
      warn("Claude Code logs found, but no sessions in them");
    } else {
      say.ok(`${sessions.length} sessions to read`, logDir.replace(os.homedir(), "~"));
    }
  }

  // 4. Credentials.
  const env = { ...readEnvFile(), ...process.env };
  const haveUrl = Boolean(env.CONTENT_SYSTEM_URL);
  const haveKey = Boolean(env.CONTENT_SYSTEM_KEY);
  if (haveUrl && haveKey) say.ok("Credentials present", path.basename(ENV_FILE));
  else {
    healthy = false;
    no("Credentials missing");
    hint(`Missing: ${[!haveUrl && "CONTENT_SYSTEM_URL", !haveKey && "CONTENT_SYSTEM_KEY"]
      .filter(Boolean).join(", ")}
Run this without arguments and it will ask for them.`);
  }

  // 5. Do they actually work? A wrong key is the failure that produces silence rather than an error,
  //    so it is checked against the real endpoint rather than assumed from the file being present.
  if (haveUrl && haveKey) {
    const target = `${String(env.CONTENT_SYSTEM_URL).replace(/\/$/, "")}/worker-triage`;
    try {
      const res = await fetch(target, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${env.CONTENT_SYSTEM_KEY}`,
        },
        // An empty batch: reaches the real endpoint with the real key and files nothing.
        body: JSON.stringify({ source: "claude_code", sessions: [] }),
      });
      if (res.ok) say.ok("Reached the server", `${res.status}`);
      else if (res.status === 401 || res.status === 403) {
        healthy = false;
        no(`Server rejected the key`, `${res.status}`);
        hint("CONTENT_SYSTEM_KEY is wrong. It is the service_role key from Project Settings → API.");
      } else {
        warn(`Server answered ${res.status}`);
        hint("Reachable, but not happy. The schedule will still run; check the URL.");
      }
    } catch (err) {
      healthy = false;
      no("Could not reach the server");
      hint(`${target}
${err.message}`);
    }
  }

  // 6. Is it actually scheduled? The whole point of 4.4.1.
  if (isScheduled()) say.ok("Scheduled", `daily at ${RUN_AT}`);
  else {
    healthy = false;
    no("Not scheduled");
    hint("Run this without arguments to set it up.");
  }

  return healthy;
}

/** Quiet true/false, so both the doctor and the installer can ask without printing. */
function isScheduled() {
  try {
    if (process.platform === "win32") {
      execFileSync("schtasks", ["/Query", "/TN", TASK_NAME], { stdio: "ignore" });
    } else if (process.platform === "darwin") {
      execFileSync("launchctl", ["list", "com.thoughtpilot.cc-agent"], { stdio: "ignore" });
    } else {
      execFileSync("systemctl", ["--user", "is-enabled", "cc-agent.timer"], { stdio: "ignore" });
    }
    return true;
  } catch {
    return false;
  }
}

/* ── Main ─────────────────────────────────────────────────────────────────── */

/* ── Main ─────────────────────────────────────────────────────────────────── */

const USAGE = `
  node cc-agent/install.mjs              set it up
  node cc-agent/install.mjs --doctor     check every reason it could fail
  node cc-agent/install.mjs --status     is it scheduled, and when did it last run
  node cc-agent/install.mjs --uninstall  stop it; the agent and its history stay
`;

if (arg === "--help" || arg === "-h") {
  title("cc-agent", "reads your Claude Code sessions");
  console.log(USAGE);
  process.exit(0);
}

if (arg === "--uninstall") {
  title("cc-agent", "removing the schedule");
  uninstall();
  process.exit(0);
}

if (arg === "--doctor") {
  title("cc-agent", "checking every reason this could fail");
  blank();
  const healthy = await doctor();
  if (healthy) done("Everything is in place.");
  else failed("Fix the above, then run it again.");
  process.exit(healthy ? 0 : 1);
}

if (arg === "--status") {
  title("cc-agent", "where it stands");
  blank();
  await doctor();
  blank();
  // The raw scheduler output underneath, for the case where the summary above is not enough.
  console.log(c.grey("  From the scheduler itself:"));
  blank();
  status();
  process.exit(0);
}

/* ── Setup ────────────────────────────────────────────────────────────────── */

title("cc-agent", "reads your Claude Code sessions (4.4)");
blank();

// Preflight. The same checks the doctor runs, so setup cannot pass on something the doctor would
// later flag — and so a missing prerequisite is named before anything is written to disk.
const major = Number(process.versions.node.split(".")[0]);
if (major < 18) {
  no(`Node ${process.versions.node}`);
  hint("The agent needs Node 18 or newer. Nothing has been changed.");
  process.exit(1);
}
ok(`Node ${process.versions.node}`);

const logDir = path.join(os.homedir(), ".claude", "projects");
if (fs.existsSync(logDir)) {
  const found = findSessions(logDir);
  if (found.length > 0) ok(`${found.length} sessions to read`, logDir.replace(os.homedir(), "~"));
  else warn("No sessions yet — it will pick them up as you work");
} else {
  // Not fatal: the schedule is still worth creating on a machine about to do the work.
  warn("No Claude Code logs on this machine yet");
  hint(`Looked in ${logDir}`);
}

const env = await ensureCredentials();
ok("Credentials ready", path.basename(ENV_FILE));

blank();
step("Setting it up");
blank();

const runner = writeRunner();
ok("Runner written", "keeps the key out of the task definition");

let where;
try {
  where = process.platform === "win32"
    ? installWindows(runner)
    : process.platform === "darwin"
    ? installMac(runner)
    : installLinux(runner);
  ok("Scheduled", where);
} catch (err) {
  no("Could not create the schedule");
  hint(`${err.message}\nRun this from a normal terminal rather than an editor's console.`);
  process.exit(1);
}

// Prove the wiring rather than declaring it. A dry run reads the real corpus and sends nothing, so
// a wrong URL or key shows up now instead of silently producing nothing for a fortnight.
blank();
step("Checking it works — reading your sessions, sending nothing");
blank();
try {
  execFileSync(process.execPath, [AGENT, "--dry-run"], {
    stdio: "inherit",
    env: { ...process.env, ...env },
  });
  blank();
  ok("Dry run completed");
} catch {
  blank();
  no("The dry run failed");
  hint("The schedule is in place, but fix the above before trusting it.\n" +
    "`--doctor` will tell you which part is wrong.");
  process.exit(1);
}

done(`Done. It runs daily at ${RUN_AT} and needs nothing from you.`);

console.log(`  ${c.bold("One thing worth doing first")}`);
console.log(`  ${c.grey("Run")} node eval/calibrate-cc.mjs ${c.grey("before trusting the threshold.")}`);
console.log(`  ${c.grey("4.4.3 is explicit that ten candidates a day is worse than none, and the")}`);
console.log(`  ${c.grey("default bar was set against a corpus that is not yours.")}`);
console.log(USAGE);
