#!/usr/bin/env node
/**
 * Embeds the session scanner into the connector, so the hosted endpoint can serve it.
 *
 * The edge function is bundled from its imports, and a file read at runtime is not an import: it
 * would work locally and 404 once deployed. So the two files go in as strings. They are generated
 * rather than hand-copied, and scanner.test.mjs fails when they are stale, because a served scanner
 * older than the one in the repository would be a second copy of the filter that nobody is reading.
 *
 *   npm run embed:scanner
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const SOURCES = ["scanner.mjs", "index.mjs"];

export function render() {
  const files = Object.fromEntries(
    SOURCES.map((f) => [f, fs.readFileSync(path.join(root, "cc-agent", f), "utf8").replace(/\r\n/g, "\n")]),
  );
  return "// GENERATED by scripts/embed-scanner.mjs from cc-agent/. Do not edit; run `npm run embed:scanner`.\n" +
    `export const SCANNER_FILES = ${JSON.stringify(files, null, 2)};\n`;
}

export const TARGET = path.join(root, "mcp-server", "generated", "scanner-files.mjs");

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  fs.writeFileSync(TARGET, render());
  console.log(`wrote ${path.relative(root, TARGET)}`);
}
